name: Maven native image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [17, 21]
        graalvm-distribution: ['liberica']
      fail-fast: false

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM ${{ matrix.graalvm-distribution }} for Java ${{ matrix.java-version }}
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.graalvm-distribution }}
          cache: 'maven'

      - name: Report Java version
        run: |
          java -version
          javac -version
          native-image --version

      - name: Install libxi-dev in Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libxi-dev

      - name: Build with Maven Wrapper (Linux)
        run: ./mvnw -V -B package
        if: runner.os == 'Linux'

      - name: Build with Maven Wrapper (Windows)
        run: .\mvnw.cmd -V -B package
        if: runner.os == 'Windows'

